const ADD_ITEM_TO_LIST = "ADD_ITEM_TO_LIST";
const REMOVE_ITEM_FROM_LIST = "REMOVE_ITEM_FROM_LIST";
const UPDATE_ITEM_FROM_LIST = "UPDATE_ITEM_FROM_LIST";

export {
  ADD_ITEM_TO_LIST,
  REMOVE_ITEM_FROM_LIST,
  UPDATE_ITEM_FROM_LIST,
}